### ISSUE TITLE
SettingsDevice missing on clean install on a Cerbo GX MK1, firmware v3.52

### ISSUE THREAD

**Issue by BjoernKellermann** [twam/dbus-lynx-distributor#3]
After clean install, I get an error SettingdDevice is missing.

`pip3 install SettingsDevice` does ot work either as requiments version is missing.

Any idea?

from /data/log/dbus-lynx-distributor/current

```
@40000000676d7dc837bebaa4     from settingsdevice import SettingsDevice
@40000000676d7dc8382fc03c ModuleNotFoundError: No module named 'settingsdevice'
@40000000676d7dc904dfb804 *** starting dbus-lynx-distributor ***
@40000000676d7dce008a3cac Library 'pyftdi' is already installed.
@40000000676d7dd227622164 Library 'pyusb' is already installed.
@40000000676d7dd32d039904 Traceback (most recent call last):
@40000000676d7dd32d03bc2c   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
@40000000676d7dd32d03c7e4     return _run_code(code, main_globals, None,
@40000000676d7dd32d03cfb4   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
@40000000676d7dd32d03db6c     exec(code, run_globals)
@40000000676d7dd32d03e33c   File "/data/dbus-lynx-distributor/dbus_lynx_distributor/__main__.py", line 11, in <module>
@40000000676d7dd32d03f2dc     from settingsdevice import SettingsDevice
@40000000676d7dd32d060a04 ModuleNotFoundError: No module named 'settingsdevice'
@40000000676d7dd3349b23e4 *** starting dbus-lynx-distributor ***
```

**Comment by BjoernKellermann** [comment]
I hacked __init__.py
Now it's working.

```
import sys
from pathlib import Path

#velib_python_path = Path(__file__).resolve().parent.parent / 'ext' / 'velib_python'
#sys.path.insert(1, str(velib_python_path))
sys.path.insert(1, '/opt/victronenergy/dbus-systemcalc-py/ext/velib_python')
#del velib_python_path

__version__ = "0.0.1"
```

**Comment by twam** [comment]
How did you install it on your device?

Smells like the git submodule in `ext` is missing.

**Comment by BjoernKellermann** [comment]
I copied the content from GitHub via scp to /data/dbus-lynx-distributor as per the manual. Then I run install.sh.
I tried it several time including uninstall.sh.

**Comment by twam** [comment]
This explains the issue. You should ‘git clone’ either with the ‘—recursive’ option or init and update the submodules after clone with the ‘git submodule’ command. Otherwise their content is missing.
